nvse_dll = shared_library(
  'nvse_1_4',
  files(
    '../Algohol/algMath.cpp',
    '../Algohol/paramTypes.cpp',
    'ArrayVar.cpp',
    'ArrayVarElementContainer.cpp',
    'CachedScripts.cpp',
    'commands_Algohol.cpp',
    'Commands_Array.cpp',
    'Commands_Console.cpp',
    'Commands_Factions.cpp',
    'Commands_Game.cpp',
    'Commands_Input.cpp',
    'Commands_Inventory.cpp',
    'Commands_InventoryRef.cpp',
    'Commands_List.cpp',
    'Commands_Math.cpp',
    'Commands_Misc.cpp',
    'Commands_MiscRef.cpp',
    'Commands_NetImmerse.cpp',
    'Commands_Packages.cpp',
    'Commands_Quest.cpp',
    'Commands_Script.cpp',
    'Commands_Scripting.cpp',
    'Commands_String.cpp',
    'Commands_UI.cpp',
    'CommandTable.cpp',
    'Compiler/AST/Visitor.cpp',
    'Compiler/Lexer/Lexer.cpp',
    'Compiler/Parser/Parser.cpp',
    'Compiler/Passes/CallTransformer.cpp',
    'Compiler/Passes/Compiler.cpp',
    'Compiler/Passes/LambdaTransformer.cpp',
    'Compiler/Passes/LoopTransformer.cpp',
    'Compiler/Passes/MatchTransformer.cpp',
    'Compiler/Passes/TreePrinter.cpp',
    'Compiler/Passes/TypeChecker.cpp',
    'Compiler/Passes/VariableResolution.cpp',
    'Compiler/Utils.cpp',
    'containers.cpp',
    'Core_Serialization.cpp',
    'EventManager.cpp',
    'FormExtraData.cpp',
    'FunctionScripts.cpp',
    'GameAPI.cpp',
    'GameBSExtraData.cpp',
    'GameData.cpp',
    'GameExtraData.cpp',
    'GameForms.cpp',
    'GameObjects.cpp',
    'GameOSDepend.cpp',
    'GameProcess.cpp',
    'GameRTTI.cpp',
    'GameScript.cpp',
    'GameSettings.cpp',
    'GameTasks.cpp',
    'GameTiles.cpp',
    'GameTypes.cpp',
    'GameUI.cpp',
    'Hooks_Animation.cpp',
    'Hooks_CreatedObject.cpp',
    'Hooks_Dialog.cpp',
    'Hooks_DirectInput8Create.cpp',
    'Hooks_Editor.cpp',
    'Hooks_Gameplay.cpp',
    'Hooks_Logging.cpp',
    'Hooks_Other.cpp',
    'Hooks_SaveLoad.cpp',
    'Hooks_Script.cpp',
    'InventoryInfo.cpp',
    'InventoryRef.cpp',
    'InventoryReference.cpp',
    'LambdaManager.cpp',
    'Loops.cpp',
    'MemoryPool.cpp',
    'NiNodes.cpp',
    'NiTypes.cpp',
    'nvse.cpp',
    'OverloadsGlobal.cpp',
    'PluginManager.cpp',
    'printf.cpp',
    'SafeWrite.cpp',
    'ScriptAnalyzer.cpp',
    'ScriptDataCache.cpp',
    'ScriptTokenCache.cpp',
    'ScriptTokens.cpp',
    'ScriptUtils.cpp',
    'Serialization.cpp',
    'StackVariables.cpp',
    'StringVar.cpp',
    'ThreadLocal.cpp',
    'UnitTests.cpp',
    'Utilities.cpp',
    'utility.cpp',
  ),
  name_prefix: '',
  include_directories: inc,
  cpp_args: common_args + [
    '-D_CRT_SECURE_NO_WARNINGS',
    '-D_USRDLL',
    '-DNVSE_EXPORTS',
    '-DRUNTIME',
    '-DRUNTIME_VERSION=0x040020D0',
    '-DNVSE_CORE',
    '/FInvse/prefix.h',
  ],
  link_with: [common_lib, loader_common_lib],
  link_args: ['/DYNAMICBASE:NO', '/MAP'],
  vs_module_defs: 'exports.def',
  install: true,
  install_dir: install_root,
)
